name: TSB Search + Demo Bots

on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  run-bots:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Search Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py &

      - name: Run Demo Bot
        env:
          DEMO_BOT_TOKEN: ${{ secrets.DEMO_BOT_TOKEN }}
        run: python demo_bot.py
